### PR TITLE
ITOS-195: Fixed m2sysbiometrics.messageFactory bean usage

### PR DESCRIPTION
**Pull request by wojtekbu**

### CODE REVIEW

**Comment by kcissewski** [comment]
@wojtekbu please fix CI errors.

**Comment by areklalo** [comment]
@wojtekbu 
These changes fix the issue of dependency in the isanteplus?

**Comment by wojtekbu** [comment]
@areklalo Yes

**Comment by areklalo** [comment]
Ok, thanks

**Pull request merged**
